name: projectapp
description: project
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any



  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.6 
  equatable: ^2.0.5
  lottie: ^3.0.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.0
  # meta: ^1.8.0
  #  flutter_lints: ^2.0.0
  shared_preferences: ^2.2.0
  go_router: ^13.0.1
  dio: ^5.3.2
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  provider: ^6.0.5
  path_provider: ^2.1.0
  firebase_ui_auth: ^1.12.1 
  image_picker: ^1.0.7
  image_cropper: ^5.0.1 
  firebase_storage: ^11.6.0
  auth_repository:
     path: package/auth_repository
  recipe_repository:
     path: package/recipe_repository 


  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_advanced_drawer: ^1.3.5
  flutter_locales: ^3.0.1 
 
  

flutter:
  uses-material-design: true
  assets:
     - assets/babcine_welcome.json
     - assets/flower.png
     - assets/food.png
    
     - assets/translations/
  fonts:
    - family: wendy
      fonts:
        - asset: assets/fontbabcia.ttf
      
          style: italic


dev_dependencies:
  firebase_auth_platform_interface: ^7.0.5
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.7
  